baseURL = "https://www.wcq.life"
title = "飘"

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[markup.highlight]
codeFences = false
style = 'emacs'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'