baseURL = "https://clay9.github.io/blog"
title = "飘"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false
style = 'manni'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[privacy]
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youTube]
    disable = false
    privacyEnhanced = false