baseURL = "https://clay9.github.io/blog"
title = "飘"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
style = 'manni'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'