baseURL = "https://www.wcq.life"
title = "飘"
theme = "LoveIt"

defaultContentLanguage = "zh-cn"
languageCode = 'zh-CN'
languageName = '简体中文'
# 是否包括中日韩文字
hasCJKLanguage = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 作者配置
[author]
  name = "wcq"
  
# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = ""
    name = "Emacs"
    url = "/emacs/index.html"
    weight = 4
  [[menu.main]]
    identifier = ""
    name = "关于"
    url = "about" #对应content目录下的about.md|about.org文件
    weight = 5

[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "light"
  # 页面头部导航栏配置
  [params.header]
    [params.header.title]
      # 标题名称
      name = "飘"

 # 页面底部信息配置
  [params.footer]
    enable = false
    
  #  搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    #  最大结果数目
    maxResultLength = 20
    #  结果内容片段长度
    snippetLength = 50
    #  搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    #  是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

# 主页配置
  [params.home]
    # 主页个人信息
    [params.home.profile]
      enable = false
   # 主页文章列表
    [params.home.posts]
      enable = false

# 文章页面全局配置
  [params.page]
  # LoveIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = false
    # LoveIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 50
    # LoveIt 更改 | 0.2.0 文章页面的分享信息设置
    [params.page.share]
    enable = false

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # table展开控制  
  [markup.tableOfContents]
    ordered = false
    startLevel = 1
    endLevel = 3


[outputs]
  home = ["HTML", "RSS", "JSON"]
