baseURL = "https://www.wcq.life"
# 网站标题
title = "飘"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"

defaultContentLanguage = "zh-cn"

languageCode = 'zh-CN'
languageName = '简体中文'

# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
# [languages]
#   [languages.zh-CN]
#     languageCode = 'zh-CN'
#     languageName = '简体中文'
#     weight = 0
#   [languages.en]
#     contentDir = 'content/en'
#     disabled = false
#     languageCode = 'en-US'
#     languageDirection = 'ltr'
#     languageName = 'English'
#     title = 'Project Documentation'
#     weight = 2
# 是否包括中日韩文字
hasCJKLanguage = true
# 是否使用 robots.txt
#enableRobotsTXT = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 作者配置
[author]
  name = "wcq"
  email = ""
  link = ""
  
# 菜单配置
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "所有文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = ""
    name = "Emacs"
    url = "/emacs/index.html"
    weight = 4
  [[menu.main]]
    identifier = ""
    name = "关于"
    url = "about" #对应content目录下的about.md文件 -- 必须是.md(org无效)
    weight = 5

[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "light"

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    [params.header.title]
      # 标题名称
      name = "飘"

 # 页面底部信息配置
  [params.footer]
    enable = false
    
  #  搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    #  最大结果数目
    maxResultLength = 20
    #  结果内容片段长度
    snippetLength = 50
    #  搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    #  是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

# 主页配置
  [params.home]
    # 主页个人信息
    [params.home.profile]
      enable = false
   # 主页文章列表
    [params.home.posts]
      enable = false

# 文章页面全局配置
  [params.page]
  # LoveIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    # LoveIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 50

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false