#+title: org for GTD
#+date: 2026-09-13 11:59:23
#+hugo_section: docs
#+hugo_bundle: 02_emacs/05_org/03_org_agenda_for_gtd
#+export_file_name: index
#+hugo_weight: 3
#+hugo_draft: false
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: :bookCollapseSection false
#+hugo_paired_shortcodes: qr %columns %details %hint mermaid %steps tabs tab


* 需求分析
  =所有的设计都是基于需求的=.
  GTD 管理的是task 和project. (详见[[file:~/my/blog/org/99_philosophy/gtd.org][GTD说明]])

  task 是非常小的任务, 符合GTD流程, 同时可以被GTD可视化展示
  project 表明了项目的层级结构, 可以被GTD可视化展示, 但自身不符合GTD流程

  #+attr_shortcode: info
  #+begin_hint
  GTD流程: capture -> refile -> archive ->review
  GTD可视化展示指 可以在org agenda中显示
  #+end_hint

  #+attr_shortcode: info
  #+begin_hint
  Project 自身应该描述项目的层级结构. 比如:

  ,* Project 我的项目
  ,** 阶段1 最小可运行环境
  ,*** 网络通信
  ,**** Server
  ,**** Client
  ,*** 日志模块
  ,** 阶段2
  ,** 阶段3
  #+end_hint

  当前需求:
  1. 有哪些task
     - [X] 他们的四象限: 紧急&&重要
     - [X] 工作量预估
     - [-] 如果是Project下的tasks
       - [X] 归属于哪个Project
       - [ ] 关联性 A task可能与B, C相关联
  2. 当前正在处理的任务
     尽可能的关注当前, 忽略其他
  3. 当某个task进行时, 快速capture我的想法, 并且自动refile
  4. 看到自己花费的时间
     - [X] 一天,一周都做了什么
     - [X] 某个project/task总共花费的时间

* 文件的设计
  每个大型Project 应该单独一个file. 比如qygame.org

  #+begin_example
    gtd
    \_ gtd_common         // 通用gtd流程文件
       \_ inbox.org       // 收集箱
       \_ task.org        // 任务清单
       \_ archive.org     // 归档文件
    \_ gtd
       \__ qygame.org     // qygame project file
  #+end_example

  gtd_common中保存的是一些通用的 Project 和 Task
  | file        | desc                                |
  |-------------+-------------------------------------|
  | inbox.org   | 不区分时间,场景, 灵光一闪即可扔进去 |
  | task.org    | 任务清单                            |
  | archive.org | 归档文件                            |

* TODO的设计
  TODO 不是执行单元, 只是代表了task的状态.
  允许TODO task 下还有子TODO subTask

  | key      | desc         |
  |----------+--------------|
  | TODO     | 等待自己处理 |
  | WAITTING | 等待他人完成 |
  | PROJECT  | 项目         |
  | DONE     | 完成         |
  | CANCEL   | 取消         |
  |----------+--------------|

* TAGS的设计
  四象限使用proirity来区分;
  TAGS为之后快速查找使用

* Effort的设计
  effort是自己对某个task工作量的预估.
  与task完成时的clock-sum-time比对, 可以更好的进行分析.

  为了方便的effort, 这里只在两处设计了提示:
  1. capture的时候, 可以输入effort. 当然为了快速capture, 这里允许输入0跳过
  2. clock-in的时候, 如果item effort还是0, 则会要求进行评估
  3. 更改task的todo state为TODO, WAITTING, PROJECT的时候, 如果effort还是0, 则会要求进行评估

* clock的设计
  org的clock已经非常好用了. 这里只是修改了clock 的显示样式


* GTD workflow
  1. caputre
     org capture 已经非常好用了, 不需要改动
  2. refile
     因为org caputre的设计, 实际上这里没必要再使用refile了
  3. archive
     现在方案:
     对于task.org, archive 到archive.org
     对于project file, 由project自己管理

* GTD 可视化
  使用org agent来负责GTD可视化. 当前主要需求:
  1. 查看各种代办事项
     - 今天的和未来的 (org-agenda-view)
     - TODO的 (org-next-view)
     - inbox中的 (org-inbox-view)
  2. 统计信息
     - 以time为视角的统计, 比如今天或这周做了哪些TODO或PROJECT
       org clock report (day/week/month/year)
     - 以PROJECT为视角的统计. 比如统计emacs PROJECT花费的时间
       org-project-view, org-archive-view 以及在特定PROJECT file中的org-colmun-view查看具体task


* 使用流程
  #+BEGIN_EXAMPLE
    |
    | capture with                                         add timestamp &&
    | template       +---------+ auto refile   +---------+   auto refile     +---------+ archive       +---------+
    +--------------->|  inbxo  |-------------->|next step|------------------>|  agenda |-------------->| archive |
    |                +---+-----+               +---------+                   +---------+               +---------+
    |                    |                                                                                  ^
    |                    |                              archiv                                              |
    |                    +----------------------------------------------------------------------------------+
    |
  #+END_EXAMPLE

  1. capture -> inbox -> auto refile
  2. 在org-next-view buffer中添加timestamp可放到org-agenda-view; 或者直接执行archive操作
  3. 在org-agenda-view buffer中调用archive
  4. 其实还有最后一步, 即把archive中的内容输出到blog中
