#+title: mac
#+date: 2024-06-04 14:36:29
#+hugo_section: docs
#+hugo_bundle: os/mac
#+export_file_name: index
#+hugo_weight: 1
#+hugo_draft: false
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: :bookCollapseSection false

* mac初步整理
** 界面的整理
   1. launchpad图标大小整理
      - 每一列图标数量
        #+begin_src sh -n
          defaults write com.apple.dock springboard-rows -int 7
        #+end_src
      - 每一行图标数量
        : defaults write com.apple.dock springboard-columns -int 7
      - 重启Launchpad
        : defaults write com.apple.dock ResetLaunchPad -bool TRUE;killall Dock
        /该指令重启launchpad的时候, 也会使launchpad的排序恢复默认值!!!/
   2. 添加空白到Dock栏
      空白能使Dock中的程序更好的归类. 按住Option可以拖动
      : defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'; killall Dock
** 状态栏调整
   按住Command之后, 鼠标可以拖动状态栏图标
** mac自带输入法 -- 简体拼音
   记录一下常用快捷键 && 配置
   1. Fn+TAB -- 短按切换ABC与简体中文, 长按大小写
   2. 建议设置选词为竖屏, 横屏容易遮挡输入

   #+attr_shortcode: info
   #+begin_hint
   不舒服的地方
   1. 输入的时候无法使用shift来切换为英文, 必须使用Fn+TAB
   2. 候选词为横屏的时候, 会遮挡住输入区域
   #+end_hint

** 关闭内置键盘
   苹果内置键盘不好用, 但是触控板非常好用.
   习惯把HHKB放在苹果键盘上, 这样可以使用HHKB+苹果触控版

   #+BEGIN_EXAMPLE shell
   # For newer versions on MacOS / alternative solution:
   # List loaded kexts for keyboard
   kextstat | grep Keyboard
   # It's going to output something like:
   # 81    0 0xffffff7f833c5000 0xb000     0xb000     com.apple.driver.AppleHIDKeyboard (208) 96DDE905-9D31-38A9-96B7-FB28573587C8 <43 6 5 3>
   # com.apple.driver.AppleHIDKeyboard is loaded kext identifier.

   # If you want to plug-in Apple Magic Keyboard / some other Bluetooth keyboard, turn it off first. Then follow the instruction below.
   # To disable keyboard:
   sudo kextunload -b com.apple.driver.AppleHIDKeyboard
   # To enable it back:
   sudo kextload -b com.apple.driver.AppleHIDKeyboard
   #+END_EXAMPLE
** 开机启动
   mac没有像linux使用init作为系统管理, 而是使用Launchd
*** launchd
    定义一个由Launchd管理服务,
    首先要有一个适用于该运行环境的程序, 比如在系统启动过程中不能使用图形交互API, 那么与用户交互的程序就不能在系统启动过程中被调用.
    其次就是定制一个launchd规则的plist文件. 它是让launchd知道哪里以及如何运行一个程序,什么时候运行, 运行的规则等等等配置文件. 最后根据运行的方式, 把这个Plist文件存放到指定的位置, 并设置好文件属性等

    | 级别                   | 目录                          |
    |------------------------+-------------------------------|
    | 操作系统级别的服务程序 | /System/Library/LaunchDaemons |
    |                        | /System/Library/LaunchAgents  |
    |------------------------+-------------------------------|
    | 本机全局               | /Library/LaunchDaemons        |
    |                        | /Library/LaunchAgents         |
    |------------------------+-------------------------------|
    | 用户级别               | ~/Library/LaunchAgents        |
    |------------------------+-------------------------------|
    Daemons是一种无用户交互的服务程序, 而Agents是用户交互
    当系统启动时, 依次执行/System/Library/LaunchDaemons 和 /Library/LaunchDaemons
    当用户登陆时, 依次执行/System/Library/LaunchAgents, /Library/LaunchAgents 和 ~/Library/LaunchAgents
*** 操作流程
    1. 编写自己的脚本, 并添加可执行权限
       如果是Daemons调用, 需要给于777权限
    2. 编写plist文件
       #+BEGIN_EXAMPLE xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key>
        <string>com.user.loginscript</string>
        <key>ProgramArguments</key>
        <array>
            <string>/path/to/my/script.sh</string>
        </array>
        <key>RunAtLoad</key>
        <true/>
    </dict>
</plist>
       #+END_EXAMPLE
    3. 根据功能, plist文件放到不同的目录
    4. load plist
       : sudo launchctl load -w ~/Library/LaunchAgents/com.service.name.plist
    5. test
       : launchctl start com.user.loginscript
* mac好用的软件
  | 软件           | 介绍                                                   | 备注   |
  |----------------+--------------------------------------------------------+--------|
  | Alfred         | [[https://www.alfredapp.com][Alfred]] 是加强版的聚焦搜索                              |        |
  | +Karabiner+      | [[https://pqrs.org/index.html][Karabiner]] 是键位映射软件                               | 已舍弃 |
  | HomeBrew       | [[https://brew.sh/index_zh-cn][HomeBrew]] 是包管理软件(类似于ubuntu下的apt)             |        |
  | Annotate       | Annotate(AppStore下载)是截屏软件, 同时支持gif录制      |        |
  | +IINA+           | [[https://www.iina.io][IINA]] 是mac下好用的视频软件                             | 已舍弃 |
  | Better Display | [[https://github.com/waydabber/BetterDisplay][Better Display]]可以更好的控制显示器, 尤其是对于2K显示器 |        |
  |----------------+--------------------------------------------------------+--------|

* Q & A
** mac卡顿处理
   1. 删除Macintosh HD/系统/资源库/Caches中的文件
   2. 删除Macintosh HD/资源库/Caches中的文件
   3. 如果以上无效, 建议更换操作系统版本, 比如从macOS high sierra更换为macOS Mojave
** ssh远程连接macos, 中文乱码
   这种情况一般是终端和服务器的字符集不匹配.
   MacOSX下默认的是utf8字符集(locale查看)，而我的对应值是空的.

   1. 在.bash_profile中增加
      #+BEGIN_EXAMPLE
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      #+END_EXAMPLE
   2. source .bash_profile
   3. locale 查看下是否设置成功
** mac崩溃原因查找
   #+BEGIN_EXAMPLE shell
   # 打印mac 24小时崩溃的原因
   # 常见原因
   # 5 -- 正常关机
   # 3 -- 硬件关机 (holding the power button)
   log show --predicate 'eventMessage contains "Previous shutdown cause"' --last 24h
   #+END_EXAMPLE
