#+title: org
#+date: 2024-01-18 18:10:47
#+hugo_section: docs
#+hugo_bundle: emacs/org
#+export_file_name: org
#+hugo_weight: 1
#+hugo_draft: false
#+hugo_auto_set_lastmod: t

org-mode一直被称为神器
主要有2大功能, 一是自身强大的文本模式, 另一个则是org-agenda
推荐阅读: [[http://doc.norang.ca/org-mode.html][org心得体会]]

* 配置
  org作为文本模式配置较少, 更多的配置是为了org-agenda.

  org文本模式下, [[https://github.com/clay9/emacs.d/blob/master/lisp/init-org-mode.el][可以配置一下简单的外观]]. 比如org-bullets.
  org-bullets更改了heading的图标, 更改了折叠的block样式为⤵. 显示更为美观


  org-agenda的配置可以参考[[https://github.com/clay9/emacs.d/blob/master/lisp/init-org-agenda-mode.el][init-org-agenda.el]]和[[https://github.com/clay9/emacs.d/blob/master/lisp/fun/init-org-agenda-fun.el][一系列自定义函数]]

* 使用
** 基本语法
*** 语法: time-stamp选择
    添加time-stamp时, 不要在calendar中移动,效率太低
    使用以下2种方式即可:
    1. 使用简约的时间格式
       17-1-1  => 2017-01-01
    2. 使用时间间隔
       now = [2016-12-28 Wed]
       +1d  => 2016-12-29

    具体见(dir) - Org mode - Dates and times - Creating timestamps - The date/time promt

*** 语法: 时间repeate
    org-mode repeate格式
    +   .+   ++区别

    1. "+"
       backlog 可以积压的item
    2. ".+"
       specific date, no backlog 在特定日期完成的item
       ep: call mother
       每周六给mother打电话, 不可积压(或者说现在的操作不会影响之前)
    3. "++"
       specific interval, no backlog 在特定间隔完成的item
       ep: change batteries
       每隔1月更换电池, 不可积压
*** 语法: table计算
    @ 表示行； $表示列
    < 表示第一;   > 表示最后；

    例子:
    @<  第一行
    $>  最后一列
    @<< 第二行(更建议使用 @2)

    对table使用C-c} 可以查看行列值

* +导出 与 org-info+
  : org-info已弃用, 不再推荐, 建议使用gnu texinfo或者ox-hugo

  org-mode有强大的导出功能, 具体可以参考官方文档.

  这里只是介绍一下org-info.js

  org-info.js 可以输出info-style xhtml, 可以作为org-mode导出html中的一种css样式补充 [[https://orgmode.org/worg/code/org-info-js/][官方文档]]

  可以在info(m), over-view(m), ppt(x)三种模式间切换. (说实话, ppt模式, 真的没啥效果:)

  拥有众多的属性值, 方便导出配置
  - path     org-info.js脚本所在路径, 可以是绝对路径或相对路径, 但必须是目录
    如果没有设置, 则默认从orgmode.org中读取
    publish , export均生效
  - home     整个org-file的根节点,  对应界面上的"HOME"按钮
    1) export 时候, 设置有效
    2) publish的时候, 设置无效
  - up       整个org-file的上层节点,对应界面上的"UP"按钮
    TODONOW 暂时不知道作用, 不设置正常使用, 界面上没有"UP"按钮
  - view     html显示样式
  - toc      整个org-file是否显示content
    publish时候 设置无效
  - ltoc     sub-heading是否显示content
    publish时候 设置无效
  - mouse    鼠标样式
  - buttons


  拥有简单的快捷键, 方便在文档node间移动. n, p, m, x, i, ?

  org-info为org-mode自带, 无须额外安装. 使用的时候, 只需指定属性然后导出即可
  #+BEGIN_EXAMPLE
  #+INFOJS_OPT: home:http://wcq.life
  #+INFOJS_OPT: view:info toc:t ltoc:t mouse:underline buttons:nil
  #+END_EXAMPLE
  org-file中的连接会被自动转换为html中的连接
  #+BEGIN_EXAMPLE 1
  # org-file:
  file:test.org

  在html中被转为
  link:test.html
  #+END_EXAMPLE


* +MobileOrg+
  : 已弃用, 不再推荐, 建议使用iphone自带软件

  方案流程
  1. PC端配置MobileOrg
     具体见.emacs
  2. 寻找WebDAV server
     现在使用的是坚果云
  3. curl同步PC端到webDAV server
     这一块非常纠结
     起初使用的ssh的scp,发现scp貌似不支持https?
     后来使用了curl, 结果发现curl不支持目录的上传.....
     导致.emacs中mobileorg的配置十分难看, 有机会应该改掉这块!
     方法有2:
     1) 换一种工具取代curl  -- 更倾向于这一种方式
     2) 使用regular expression -- 貌似curl支持的不好


  总览图
  #+BEGIN_EXAMPLE artist
    +-----------+ push          +--------------+
    | PC端      |-------------->| WwbDAV server|
    |           |<--------------|              |
    +-----------+ pull          +--------------+
                                    |      ^
                                    |      |
                                    |      |
                                    v      |
                                +--------------+
                                | Mobile       |
                                |              |
                                +--------------+
  #+END_EXAMPLE
