name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - uses: actions/checkout@v3
        with:
          repository: clay9/emacs.d
          path: ./emacs.d
          submodules: true

      - run: |
          sudo apt install emacs texinfo -y
          mv ./emacs.d ~/emacs.d && ln -s ~/emacs.d ~/.emacs.d
      - run: |
          emacs -u $USER --script ~/.emacs.d/script/export-org-to-md.el
          emacs -u $USER --script ~/.emacs.d/script/export-org-to-texi2html.el
          rm -rf ~/emacs.d
          mv content/posts/about.md content/
          echo "ls content" && ls -al content
          echo "ls content/posts" && ls -al content/posts
          echo "ls pwd" && echo $PWD
          echo "ls ~" && ls -al ~

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
